name: Deploy Docker App

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest # Запуск на последней версии Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Шаг для получения кода из репозитория

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # Устанавливаем Docker Buildx для сборки образов

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username из секретов
          password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password из секретов

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: . # Контекст сборки (всё содержимое репозитория)
          push: true # Пушим образы на Docker Hub
          tags: anastasiiaskreka/nestjs-server:latest, anastasiiaskreka/nextjs-client:latest # Указываем теги для образов

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3 # Для подключения по SSH и развертывания
        with:
          host: ${{ secrets.SERVER_IP }} # IP сервера из секретов
          username: ${{ secrets.SERVER_USER }} # Пользователь для SSH из секретов
          key: ${{ secrets.SERVER_SSH_KEY }} # Приватный ключ для подключения из секретов
          script: |
            cd /var/www/my-app  # Указываем путь к директории с проектом на сервере
            git pull origin main  # Обновляем код на сервере
            docker-compose down  # Останавливаем старые контейнеры
            docker-compose up --build -d  # Запускаем новые контейнеры с пересборкой
